{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'AnyZip',
          'size':(401, 299),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit',
                   'command':'exit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'extractone', 
    'position':(78, 26), 
    'label':u'Extract one', 
    },

{'type':'Button', 
    'name':'include', 
    'position':(158, 26), 
    'label':u'Add', 
    },

{'type':'Choice', 
    'name':'format', 
    'position':(73, 53), 
    'size':(130, -1), 
    'items':[u'Detecting...'], 
    'stringSelection':u'Detecting...', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(25, 58), 
    'text':u'Format', 
    'toolTip':u'Auto-detect/Ignore for opening', 
    },

{'type':'PasswordField', 
    'name':'pw', 
    'position':(72, 76), 
    'size':(125, -1), 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(16, 70), 
    'text':u'Password:', 
    'toolTip':u'(for encrypted files only)', 
    },

{'type':'List', 
    'name':'filenamesdis', 
    'position':(3, 161), 
    'items':[], 
    'toolTip':u'Used with extract one.', 
    },

#{'type':'Button', 
    #'name':'zip', 
    #'position':(233, 25), 
    #'label':u'zippify', 
    #},

{'type':'StaticText', 
    'name':'load', 
    'position':(353, 228), 
    'toolTip':u'Easter egg!', 
    'visible':False, 
    },

{'type':'Button', 
    'name':'run', 
    'position':(310, 25), 
    'label':u'run', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(23, 94), 
    'text':u'Open...', 
    },

{'type':'Button', 
    'name':'browse2', 
    'position':(205, 126), 
    'label':u'Browse...', 
    'toolTip':u'If not found, DOES NOT SHOW ERROR MESSAGE,It does when you do the action.', 
    },

#{'type':'TextField', 
    #'name':'secondary', 
    #'position':(71, 127), 
    #'size':(127, -1), 
    #'toolTip':u'combine/compress from/depress to/run with args', 
    #},

{'type':'Button', 
    'name':'browse', 
    'position':(204, 101), 
    'label':u'Browse...', 
    'toolTip':u'If not found, DOES NOT SHOW ERROR MESSAGE', 
    },

{'type':'TextField', 
    'name':'url', 
    'position':(70, 101), 
    'size':(127, -1), 
    'toolTip':u'View, edit, delete, extract this', 
    },

{'type':'StaticLine', 
    'name':'StaticLine2', 
    'position':(350, 225), 
    'size':(1, 20), 
    'layout':'horizontal', 
    },

#{'type':'Button', 
    #'name':'combine', 
    #'position':(310, 0), 
    #'label':u'combine', 
    #},

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(1, 225), 
    'size':(390, -1), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'msg', 
    'position':(0, 226), 
    'text':u'Ready', 
    'toolTip':u"Easter egg:I'm ready ,I'm ready", 
    },

#{'type':'Button', 
    #'name':'delete', 
    #'position':(235, 0), 
    #'label':u'delete', 
    #},

{'type':'Button', 
    'name':'extract', 
    'position':(160, 0), 
    'label':u'extract', 
    },

#{'type':'Button', 
    #'name':'edit', 
    #'position':(80, 0), 
    #'label':u'edit', 
    #},

{'type':'Button', 
    'name':'view', 
    'position':(1, 0), 
    'label':u'view', 
    },

] # end components
} # end background
] # end backgrounds
} }
